#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROLES_DIR="$SCRIPT_DIR/roles"
TEMPLATES_DIR="$SCRIPT_DIR/templates"
MARKER_FILE=".claude-role"

# --- Helpers ---

usage() {
    cat <<EOF
Usage:
  $(basename "$0") <role> <target-repo>    Deploy a role to a repo
  $(basename "$0") --refresh               Re-deploy to all previously configured repos
  $(basename "$0") --remove <target-repo>  Remove deployed config from a repo
  $(basename "$0") --list                  List available roles

Roles:
$(list_roles)

Examples:
  $(basename "$0") ios-developer ../PyroFoundation
  $(basename "$0") qa-engineer ../PyroAppStore
  $(basename "$0") --refresh
EOF
}

list_roles() {
    for f in "$ROLES_DIR"/*.md; do
        local name
        name="$(basename "$f" .md)"
        local title
        title="$(head -1 "$f" | sed 's/^# Role: //')"
        printf "  %-20s %s\n" "$name" "$title"
    done
}

build_claude_md() {
    local role_file="$1"
    local role_name
    role_name="$(basename "$role_file" .md)"

    cat <<EOF
<!-- Generated by pyro-claude-utils — do not edit manually -->
<!-- Role: $role_name | Regenerate with: ./deploy.sh $role_name <repo> -->

$(cat "$TEMPLATES_DIR/base.md")

---

$(cat "$role_file")
EOF
}

deploy_role() {
    local role_name="$1"
    local target_dir="$2"

    local role_file="$ROLES_DIR/$role_name.md"
    if [[ ! -f "$role_file" ]]; then
        echo "Error: unknown role '$role_name'"
        echo "Available roles:"
        list_roles
        exit 1
    fi

    # Resolve to absolute path
    target_dir="$(cd "$target_dir" 2>/dev/null && pwd)" || {
        echo "Error: target directory '$2' does not exist"
        exit 1
    }

    local target_file="$target_dir/CLAUDE.md"
    local marker="$target_dir/$MARKER_FILE"

    # Warn if overwriting a non-managed CLAUDE.md
    if [[ -f "$target_file" && ! -f "$marker" ]]; then
        echo "Warning: $target_file exists but was not deployed by this tool."
        read -rp "Overwrite? [y/N] " confirm
        if [[ "$confirm" != [yY] ]]; then
            echo "Aborted."
            exit 0
        fi
    fi

    build_claude_md "$role_file" > "$target_file"

    # Write marker with metadata
    cat > "$marker" <<MARKER
role=$role_name
source=$SCRIPT_DIR
deployed=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
MARKER

    echo "Deployed '$role_name' to $target_file"
}

refresh_all() {
    local found=0
    local parent_dir
    parent_dir="$(dirname "$SCRIPT_DIR")"

    for marker in "$parent_dir"/*/"$MARKER_FILE"; do
        [[ -f "$marker" ]] || continue
        found=1

        local target_dir
        target_dir="$(dirname "$marker")"
        local role_name
        role_name="$(grep '^role=' "$marker" | cut -d= -f2)"

        if [[ -z "$role_name" ]]; then
            echo "Warning: invalid marker in $target_dir, skipping"
            continue
        fi

        echo "Refreshing $(basename "$target_dir") with role '$role_name'..."
        deploy_role "$role_name" "$target_dir"
    done

    if [[ "$found" -eq 0 ]]; then
        echo "No deployed repos found in $parent_dir"
        exit 1
    fi
}

remove_config() {
    local target_dir="$1"
    target_dir="$(cd "$target_dir" 2>/dev/null && pwd)" || {
        echo "Error: target directory '$1' does not exist"
        exit 1
    }

    local target_file="$target_dir/CLAUDE.md"
    local marker="$target_dir/$MARKER_FILE"

    if [[ ! -f "$marker" ]]; then
        echo "Error: $target_dir was not deployed by this tool (no $MARKER_FILE found)"
        exit 1
    fi

    rm -f "$target_file" "$marker"
    echo "Removed CLAUDE.md and marker from $target_dir"
}

# --- Main ---

if [[ $# -eq 0 ]]; then
    usage
    exit 1
fi

case "$1" in
    --list|-l)
        echo "Available roles:"
        list_roles
        ;;
    --refresh|-r)
        refresh_all
        ;;
    --remove)
        [[ $# -ge 2 ]] || { echo "Error: --remove requires a target directory"; exit 1; }
        remove_config "$2"
        ;;
    --help|-h)
        usage
        ;;
    *)
        [[ $# -ge 2 ]] || { echo "Error: must specify both <role> and <target-repo>"; usage; exit 1; }
        deploy_role "$1" "$2"
        ;;
esac
